export default {
  'FETCH_ACCOUNTS': 'FETCH_ACCOUNTS',
  'FETCH_ACCOUNTS_PENDING': 'FETCH_ACCOUNTS_PENDING',
  'FETCH_ACCOUNTS_SUCCESS': 'FETCH_ACCOUNTS_SUCCESS',
  'FETCH_ACCOUNTS_ERROR': 'FETCH_ACCOUNTS_ERROR'
}
