export default {
  'FETCH_TRANSACTIONS': 'FETCH_TRANSACTIONS',
  'FETCH_TRANSACTIONS_PENDING': 'FETCH_TRANSACTIONS_PENDING',
  'FETCH_TRANSACTIONS_SUCCESS': 'FETCH_TRANSACTIONS_SUCCESS',
  'FETCH_TRANSACTIONS_ERROR': 'FETCH_TRANSACTIONS_ERROR'
}
